from __future__ import annotations

from typing import TYPE_CHECKING

import structlog
from jinja2 import Template

if TYPE_CHECKING:
    from .agent import Newsletter

logger = structlog.get_logger(__name__)

HTML_TEMPLATE = Template("""\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{{ newsletter.title }}</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
         max-width: 700px; margin: 0 auto; padding: 20px; background: #f8f9fa; color: #1a1a2e; }
  .header { background: linear-gradient(135deg, #0f3460, #16213e); color: #fff;
             padding: 30px; border-radius: 12px; margin-bottom: 24px; }
  .header h1 { margin: 0 0 8px 0; font-size: 26px; }
  .header .date { opacity: 0.85; font-size: 14px; }
  .header .summary { margin-top: 12px; font-size: 15px; opacity: 0.9; }
  .section { background: #fff; border-radius: 10px; padding: 24px;
             margin-bottom: 18px; box-shadow: 0 1px 3px rgba(0,0,0,0.08); }
  .section h2 { color: #0f3460; margin-top: 0; font-size: 20px;
                 border-bottom: 2px solid #e94560; padding-bottom: 8px; }
  .section .summary { color: #555; font-size: 14px; margin-bottom: 16px; }
  .item { margin-bottom: 14px; padding-bottom: 14px; border-bottom: 1px solid #eee; }
  .item:last-child { border-bottom: none; margin-bottom: 0; padding-bottom: 0; }
  .item h3 { margin: 0 0 4px 0; font-size: 16px; }
  .item h3 a { color: #0f3460; text-decoration: none; }
  .item h3 a:hover { color: #e94560; }
  .item .meta { font-size: 12px; color: #888; margin-bottom: 4px; }
  .item .desc { font-size: 14px; color: #444; line-height: 1.5; }
  .tags { display: flex; flex-wrap: wrap; gap: 4px; margin-top: 6px; }
  .tag { background: #e8eaf6; color: #3949ab; padding: 2px 8px;
         border-radius: 12px; font-size: 11px; }
  .paper { margin-bottom: 16px; padding-bottom: 16px; border-bottom: 1px solid #eee; }
  .paper:last-child { border-bottom: none; }
  .paper h3 { margin: 0 0 4px 0; font-size: 15px; }
  .paper h3 a { color: #0f3460; text-decoration: none; }
  .paper .authors { font-size: 12px; color: #666; font-style: italic; }
  .paper .abstract { font-size: 13px; color: #444; line-height: 1.5; margin-top: 6px; }
  .footer { text-align: center; font-size: 12px; color: #999; margin-top: 24px; padding: 16px; }
</style>
</head>
<body>
<div class="header">
  <h1>{{ newsletter.title }}</h1>
  <div class="date">{{ newsletter.date.strftime('%A, %B %d, %Y') }}</div>
  {% if newsletter.topic_summary %}
  <div class="summary">{{ newsletter.topic_summary }}</div>
  {% endif %}
</div>

{% for section in newsletter.sections %}
<div class="section">
  <h2>{{ section.title }}</h2>
  {% if section.summary %}<div class="summary">{{ section.summary }}</div>{% endif %}

  {% for item in section.items %}
  <div class="item">
    <h3><a href="{{ item.url }}">{{ item.title }}</a></h3>
    <div class="meta">{{ item.source }}{% if item.published %} &middot; \
{{ item.published.strftime('%b %d, %Y') }}{% endif %}</div>
    <div class="desc">{{ item.summary }}</div>
    {% if item.tags %}
    <div class="tags">{% for tag in item.tags %}<span class="tag">{{ tag }}</span>{% endfor %}</div>
    {% endif %}
  </div>
  {% endfor %}

  {% for paper in section.papers %}
  <div class="paper">
    <h3><a href="{{ paper.url }}">{{ paper.title }}</a></h3>
    <div class="authors">{{ paper.authors | join(', ') }}</div>
    <div class="abstract">{{ paper.abstract[:300] }}{% if paper.abstract | length > 300 %}...{% endif %}</div>
  </div>
  {% endfor %}
</div>
{% endfor %}

<div class="footer">
  Generated by Physical AI Agent &middot; {{ newsletter.date.strftime('%Y-%m-%d %H:%M UTC') }}
</div>
</body>
</html>
""")

MARKDOWN_TEMPLATE = Template("""\
# {{ newsletter.title }}

**{{ newsletter.date.strftime('%A, %B %d, %Y') }}**

{{ newsletter.topic_summary }}

---

{% for section in newsletter.sections %}
## {{ section.title }}

{% if section.summary %}*{{ section.summary }}*{% endif %}

{% for item in section.items %}
### [{{ item.title }}]({{ item.url }})

**{{ item.source }}**{% if item.published %} · {{ item.published.strftime('%b %d, %Y') }}{% endif %}

{{ item.summary }}

{% if item.tags %}Tags: {% for tag in item.tags %}`{{ tag }}`{% if not loop.last %} {% endif %}{% endfor %}{% endif %}

{% endfor %}
{% for paper in section.papers %}
### [{{ paper.title }}]({{ paper.url }})

*{{ paper.authors | join(', ') }}*

{{ paper.abstract[:300] }}{% if paper.abstract | length > 300 %}...{% endif %}

{% endfor %}
---

{% endfor %}

*Generated by Physical AI Agent · {{ newsletter.date.strftime('%Y-%m-%d %H:%M UTC') }}*
""")


class NewsletterCompiler:
    def __init__(self) -> None:
        self.log = logger.bind(component="newsletter")

    def compile_newsletter(self, newsletter: Newsletter) -> Newsletter:
        self.log.info("compiling_newsletter", title=newsletter.title)
        newsletter.html_content = self.format_html(newsletter)
        newsletter.markdown_content = self.format_markdown(newsletter)
        self.log.info(
            "newsletter_compiled",
            html_len=len(newsletter.html_content),
            md_len=len(newsletter.markdown_content),
        )
        return newsletter

    def format_html(self, newsletter: Newsletter) -> str:
        self.log.debug("formatting_html")
        return HTML_TEMPLATE.render(newsletter=newsletter)

    def format_markdown(self, newsletter: Newsletter) -> str:
        self.log.debug("formatting_markdown")
        return MARKDOWN_TEMPLATE.render(newsletter=newsletter)
